[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = ["@chainlink/contracts/=lib/chainlink-brownie-contracts/contracts/"]
ffi = true
# keep ffi off as long as possible, it lets foundry run scripts on your machine

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
